# Generated by Django 4.2.7 on 2023-11-21 11:34

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criacao'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ultima_alteracao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima alteracao'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='utilizador_criacao',
            field=models.ManyToManyField(related_name='utilizador_criacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
