# Generated by Django 4.2.7 on 2023-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_pacientes_data_criacao_pacientes_ultima_alteracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='inactivo',
            field=models.BooleanField(default=False),
        ),
    ]
