# Generated by Django 4.2.7 on 2023-11-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_remove_paciente_numero_beneficiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('B', 'BI'), ('P', 'Passaporte'), ('CE', 'Cartao de eleitor'), ('D', 'DIRE'), ('O', 'Outro')], max_length=200, null=True),
        ),
    ]
