# Generated by Django 4.2.7 on 2023-11-23 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0006_paciente_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nacionslidade',
            new_name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='utilizador_criacao',
        ),
        migrations.AddField(
            model_name='paciente',
            name='utilizador_criacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
