# Generated by Django 4.2.7 on 2024-02-28 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0012_alter_paciente_estado_civil_alter_paciente_sexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=18)),
                ('local_nascimento', models.CharField(max_length=200, null=True)),
                ('numero_contribuinte', models.IntegerField()),
                ('morada', models.CharField(max_length=200, null=True)),
                ('telefone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profissao', models.CharField(max_length=200, null=True)),
                ('observacoes', models.TextField(null=True)),
                ('tipo_documento', models.CharField(choices=[('BI', 'BI'), ('Passaporte', 'Passaporte'), ('Carta de conducao', 'Carta de conducao'), ('Cartao de eleitor', 'Cartao de eleitor'), ('DIRE', 'DIRE'), ('Outro', 'Outro')], max_length=200, null=True)),
                ('numero_documento', models.CharField(max_length=200)),
                ('data_emissao_documento', models.DateField(null=True, verbose_name='data de emissao')),
                ('data_validade_documento', models.DateField(null=True, verbose_name='data de validade')),
                ('nacionalidade', models.CharField(max_length=200, null=True)),
                ('estado_civil', models.CharField(choices=[('Solteiro/a', 'Solteiro/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viuvo/a', 'Viuvo/a'), ('Outro', 'Outro')], max_length=12)),
                ('nome_pai', models.CharField(max_length=200, null=True)),
                ('nome_mae', models.CharField(max_length=200, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criacao')),
                ('ultima_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima alteracao')),
                ('utilizador_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
