# Generated by Django 4.2.7 on 2024-03-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_especialidade_medico_alter_paciente_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='data_nascimento',
        ),
    ]
