# Generated by Django 4.2.7 on 2024-02-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='local_nascimento',
            new_name='Especialidade',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='data_validade_documento',
            new_name='data_validade_ordem',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='numero_documento',
            new_name='numero_ordem',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='local_nascimento',
            new_name='especialidade',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='data_emissao_documento',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='numero_contribuinte',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='profissao',
        ),
    ]
