# Generated by Django 4.2.7 on 2024-02-29 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0014_rename_local_nascimento_medico_especialidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='Especialidade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='local_nascimento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criacao')),
                ('ultima_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima alteracao')),
                ('inactivo', models.BooleanField(default=False)),
                ('utilizador_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
