# Generated by Django 4.2.7 on 2024-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_remove_medico_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='data de nascimento'),
        ),
    ]
