# Generated by Django 5.0.3 on 2024-03-16 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0015_medico_data_nascimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data da consulta')),
                ('observacoes', models.TextField(null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criacao consulta')),
                ('ultima_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima alteracao consulta')),
                ('inactivo', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
                ('utilizador_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_criacao_consulta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data do exame')),
                ('observacoes', models.TextField(null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criacao exame')),
                ('ultima_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima alteracao exame')),
                ('inactivo', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
                ('utilizador_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_criacao_exame', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_receita', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data da receita')),
                ('observacoes', models.TextField(null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criacao receita')),
                ('ultima_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima alteracao receita')),
                ('inactivo', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
                ('utilizador_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_criacao_receita', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
